# Generated by Django 3.2.4 on 2021-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
