# Generated by Django 3.2.4 on 2021-07-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expense_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='expense',
            name='total_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
